# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0f934fbede275479e65237c16ee9a0e220805daa082872ecf66b41b1f3851640866175a589470f78e9c8e20aaaaf54d603f47eee37c26006c6340626a934528

test:
  secret_key_base: be0adb8c7d16f73197ccfb5c35e035704594adcc75849e8b0350cfdc6575452661a9337550024f8a0516a9f2f30841c8937dd7f74dd6c9797d9df5aaece94c7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
